---
- name: Creating Grafana folder
  file:
    dest: '{{ grafana_path }}/grafana/dashboards'
    state: directory
    owner: grafana
    group: grafana
    mode: 0755

- name: Grafana sysconfig file transfer
  template:
    src: 'grafana-server.j2'
    dest: '/etc/sysconfig/grafana-server'
    owner: root
    group: root
    mode: 0664
  register: conf_updated

- name: Grafana Dashboards configuration
  template:
    src: 'dashboards.yaml.j2'
    dest: '/etc/grafana/provisioning/dashboards/{{ item }}.yaml'
    owner: root
    group: grafana
    mode: 0640
  with_items: '{{ grafana_dashboards }}'
  register: dash_updated

- name: Grafana Datasources configuration
  template:
    src: 'datasources/{{ item }}.yaml.j2'
    dest: '/etc/grafana/provisioning/datasources/{{ item }}.yaml'
    owner: root
    group: grafana
    mode: 0640
  with_items:
    - '{{ grafana_datasources }}'
  register: ds_updated

- name: Grafana Analytics configuration
  lineinfile:
    state: present
    dest: '/etc/grafana/grafana.ini'
    insertafter: '\[analytics\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^reporting_enabled =', line: 'reporting_enabled = {{ grafana_arg.reporting_enabled }}' }
    - { regexp: '^check_for_updates =', line: 'check_for_updates = {{ grafana_arg.check_for_updates }}' }

- name: Grafana Security configuration
  lineinfile:
    state: present
    dest: '/etc/grafana/grafana.ini'
    insertafter: '\[security\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^admin_user =',     line: 'admin_user = {{ grafana_admin_user }}' }
    - { regexp: '^admin_password =', line: 'admin_password = {{ grafana_admin_password }}' }
  register: secu_updated

- name: Grafana UI theme configuration
  lineinfile:
    state: present
    dest: '/etc/grafana/grafana.ini'
    insertafter: '\[users\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^default_theme =', line: 'default_theme = {{ grafana_arg.default_theme }}' }
