---
- name: Grafana LDAP configuration.
  lineinfile:
    state: present
    dest: '/etc/grafana/grafana.ini'
    insertafter: '\[auth.ldap\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^enabled =',       line: 'enabled = {{ grafana_ldap_enabled | bool | to_json }}' }
    - { regexp: '^allow_sign_up =', line: 'allow_sign_up = {{ grafana_ldap_allow_sign_up | bool | to_json  }}' }

- name: Grafana LDAP configuration file transfer.
  template:
    src: 'ldap.toml.j2'
    dest: '/etc/grafana/ldap.toml'
    backup: 'yes'
    owner: 'root'
    group: 'grafana'
    mode: '0640'
  when: grafana_ldap_enabled | bool
  no_log: true