---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Configure the grafana firewall
  include: 'firewall.yml'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Configuration the grafana
  include: 'configureation.yml'

- name: Install the Grafana plugins
  include: 'plugin.yml'

- name: Enable LDAP Authentication
  include: 'ldap.yml'

- name: Reload the grafana service
  shell: echo ''
  notify: 'Ensure grafana service is enabled'
  when: soft_updated is changed or conf_updated is changed or secu_updated is changed or ds_updated is changed or dash_updated is changed or plug_updated is changed or ldap_enable is changed or ldap_config is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Manage Grafana dashboards
  include: 'dashboard.yml'

- include_tasks: 'register.yml'
  when: consul_public_register
