---
- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_http_port }}/v1/agent/service/register'
    method: 'PUT'
    headers:
      X-Consul-Token: "{{ consul_exporter_token }}"
    body: '{"ID":"{{ inventory_hostname | upper }}_grafana_exporter","name":"grafana_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ grafana_port }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ grafana_port }}/metrics","interval":"60s","tls_skip_verify":true,"method":"GET","timeout":"5s"}]}'
    body_format: 'json'
  environment:
    no_proxy: '{{ item }}'
  with_items: '{{ consul_clients }}'
  no_log: true