{
 "title": "Azure Cache for Redis",
 "tags": [ "Insight" ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_redis, resourceID)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "azure_redis{aggregation=\"average\",metric=\"serverLoad\",resourceID=~\"/subscriptions/$subscription/.*\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "azure_redis{aggregation=\"average\",metric=\"serverLoad\",resourceID=~\"/subscriptions/$subscription/resource[gG]roups/$resourcegroup/providers/Microsoft.Cache/Redis/.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Miss Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cachemissrate\",resourceID=~\".*/$host\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemorypercentage\",resourceID=~\".*/$host\"}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per Second" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"operationsPerSecond\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Saturation and Server Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"percentProcessorTime\",resourceID=~\".*/$host\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"serverLoad\",resourceID=~\".*/$host\"}",
     "legendFormat": "Server Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemory\",resourceID=~\".*/$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"usedmemoryRss\",resourceID=~\".*/$host\"}",
     "legendFormat": "Rss"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"evictedkeys\",resourceID=~\".*/$host\"}",
     "legendFormat": "Evicted"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"expiredkeys\",resourceID=~\".*/$host\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"totalkeys\",resourceID=~\".*/$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"getcommands\",resourceID=~\".*/$host\"}",
     "legendFormat": "Gets"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"setcommands\",resourceID=~\".*/$host\"}",
     "legendFormat": "Sets"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"connectedclients\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cacheRead\",resourceID=~\".*/$host\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "azure_redis{aggregation=\"average\",metric=\"cacheWrite\",resourceID=~\".*/$host\"}",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}