{
 "title": "Consul Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(consul_up, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(consul_raft_leader{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(consul_raft_peers{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(consul_serf_lan_members{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Catalog Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(consul_catalog_services{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Total Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (check)(consul_health_service_status{environment=\"$environment\"} == 1))"
    }
   ]
  },
  {
   "title": "Critical Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (check)(consul_health_service_status{status=\"critical\",environment=\"$environment\"} == 1))"
    }
   ]
  }
 ]
}