{
 "title": "Cross Server Graphs",
 "tags": [ "Insight" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   { "name": "group", "label": "Group", "query": "label_values(os_info, group)" },
   {
    "name": "host",
    "label": "Host",
    "query": "os_info{group=~\"$group\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(count(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (count(wmi_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0))",
     "legendFormat": "Instance"
    },
    {
     "expr": "(sum(wmi_cs_logical_processors{instance=~\"$host\"}) or vector(0)) + (count(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"}) or vector(0))",
     "legendFormat": "Processor"
    },
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance=~\"$host\"}) or vector(0)) + (sum(wmi_os_visible_memory_bytes{instance=~\"$host\"}) or vector(0))) / 1024 / 1024 / 1005",
     "legendFormat": "Memory in Gigabytes"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) or vector(0)) + (sum(wmi_logical_disk_size_bytes{instance=~\"$host\"}) or vector(0))) / 1024 / 1024 / 1023.5",
     "legendFormat": "Storage in Gigabytes"
    }
   ]
  },
  {
   "title": "Specifications",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "os_info{instance=~\"$host\"}"
    },
    {
     "expr": "sum by(instance)(wmi_cs_logical_processors{instance=~\"$host\"}) or count by(instance)(node_cpu_seconds_total{instance=~\"$host\",mode=\"user\"})"
    },
    {
     "expr": "(sum by(instance)(node_memory_MemTotal_bytes{instance=~\"$host\"}) or sum by(instance)(wmi_os_visible_memory_bytes{instance=~\"$host\"})) / 1024 / 1024 / 1005"
    },
    {
     "expr": "(sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) or sum by(instance)(wmi_logical_disk_size_bytes{instance=~\"$host\"})) / 1024 / 1024 / 1023.5"
    },
    {
     "expr": "(time() - wmi_system_system_up_time{instance=~\"$host\"}) or ((time() - node_boot_time_seconds{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Combine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(1 - avg by(instance)(irate(node_cpu_seconds_total{instance=~\"$host\",mode='idle'}[5m]))) or (1 - avg by(instance)(irate(wmi_cpu_time_total{mode=\"idle\", instance=~\"$host\"}[5m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$host\"} - (node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"})) / node_memory_MemTotal_bytes{instance=~\"$host\"}) or ((wmi_cs_physical_memory_bytes{instance=~\"$host\"} - wmi_os_physical_memory_free_bytes{instance=~\"$host\"}) / wmi_cs_physical_memory_bytes{instance=~\"$host\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "graph",
   "description": "Percentage of usage disk space on mount for Linux.\nPercentage of usage disk space exclude reserve partition for Windows.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(1- sum by(instance)(node_filesystem_free_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}) / sum by(instance)(node_filesystem_size_bytes{instance=~\"$host\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})) or (1- sum by(instance)(wmi_logical_disk_free_bytes{instance=~\"$host\"}) / sum by(instance)(wmi_logical_disk_size_bytes{instance=~\"$host\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(sum(irate(node_network_receive_bytes_total{instance=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_bytes_total{instance=~\"$host\", device!=\"lo\"}[5m])) by (instance)) or (sum(rate(wmi_net_bytes_sent_total{instance=~\"$host\"}[5m])) by (instance) + sum(rate(wmi_net_bytes_received_total{instance=~\"$host\"}[5m])) by (instance))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}