{
 "title": "Elasticsearch Overview",
 "tags": [ "Insight" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_cluster_health_status, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"})*2)+sum(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"})) / (count(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Total Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "elasticsearch_clusterinfo_version_info{cluster=\"$cluster\"}"
    },
    {
     "expr": "avg by (instance)(elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Documents indexed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Queris/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=\"$cluster\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=\"$cluster\",type!=\"management\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=\"$cluster\",type!=\"management\"}[5m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Transport Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes out (-) / bytes in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=\"$cluster\"} * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}