{
 "title": "JMX Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [ "Insight" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   { "name": "group", "label": "Group", "query": "label_values(jvm_info, group)" },
   {
    "name": "host",
    "label": "Host",
    "query": "jvm_info{group=\"$group\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"$host\",service=\"jmx_exporter\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "jvm_info{instance=\"$host\"}",
     "legendFormat": "{{ runtime }}<br>{{version}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Heap usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$host\"} / jvm_memory_bytes_max{area=\"heap\",instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$host\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "nonHeap usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=\"$host\"} / jvm_memory_bytes_max{area=\"nonheap\",instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "GC collection time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{instance=\"$host\"} / jvm_gc_collection_seconds_count{instance=\"$host\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Servlet request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_servlet_requestcount_total{instance=\"$host\"}",
     "legendFormat": "{{ servlet }}"
    }
   ]
  },
  {
   "title": "Connector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{instance=\"$host\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$host\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$host\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$host\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$host\",service=\"jmx_exporter\"}",
     "legendFormat": "Process file descriptors"
    },
    {
     "expr": "process_max_fds{instance=\"$host\",service=\"jmx_exporter\"}",
     "legendFormat": "Maximum file descriptors"
    }
   ]
  }
 ]
}