{
 "title": "Minio Overview",
 "description": "minio dashboard",
 "tags": [
  "object-storage",
  "Insight"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(minio_disks_offline, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 3, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(disk_storage_used{tenant=\"$tenant\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(disk_storage_total{tenant=\"$tenant\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 9, "w": 11, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_rx_bytes_total{tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(s3_tx_bytes_total{tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Transmited"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code, value)(promhttp_metric_handler_requests_total{tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Total disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disks_total{tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Offline disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disks_offline{tenant=\"$tenant\"})"
    }
   ]
  }
 ]
}