{
 "title": "Minio",
 "description": "minio dashboard",
 "tags": [
  "object-storage",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(minio_offline_disks , tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - process_start_time_seconds{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Total disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(minio_total_disks{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Offline disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(minio_offline_disks{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "description": "Totals of all disks",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(minio_disk_storage_used_bytes{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_open_fds{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(code, value)(promhttp_metric_handler_requests_total{service=\"minio_exporter\",tenant=\"$tenant\"})"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(minio_network_received_bytes_total{service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Received: "
    },
    {
     "expr": "sum(rate(minio_network_sent_bytes_total{service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "HTTP Requests duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(minio_http_requests_duration_seconds_sum{request_type=\"GET\",service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(minio_http_requests_duration_seconds_sum{request_type=\"POST\",service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(minio_http_requests_duration_seconds_sum{request_type=\"PUT\",service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(minio_http_requests_duration_seconds_sum{request_type=\"HEAD\",service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "HEAD"
    },
    {
     "expr": "sum(rate(minio_http_requests_duration_seconds_sum{request_type=\"DELETE\",service=\"minio_exporter\",tenant=\"$tenant\"}[5m]))",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}