{
 "title": "Azure Virtual network gateway",
 "tags": [ "Network" ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_virtualnetworkgateway, resourceID)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"AverageBandwidth\",resourceID=~\"/subscriptions/$subscription/.*\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"AverageBandwidth\",resourceID=~\"/subscriptions/$subscription/resource[gG]roups/$resourcegroup/providers/Microsoft.Network/virtualNetworkGateways/.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "per Second" }
   ],
   "targets": [
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"AverageBandwidth\",resourceID=~\".*/$host\"}",
     "legendFormat": "Site-to-Site"
    },
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelAverageBandwidth\",resourceID=~\".*/$host\"}",
     "legendFormat": "Tunnel"
    },
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"P2SBandwidth\",resourceID=~\".*/$host\"}",
     "legendFormat": "Point-to-Site"
    }
   ]
  },
  {
   "title": "Tunnel Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelEgressBytes\",resourceID=~\".*/$host\"}",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelIngressBytes\",resourceID=~\".*/$host\"}",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "Tunnel Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelEgressPackets\",resourceID=~\".*/$host\"}",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelIngressPackets\",resourceID=~\".*/$host\"}",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "Traffic packet drop",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelEgressPacketDropTSMismatch\",resourceID=~\".*/$host\"}",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "azure_virtualnetworkgateway{aggregation=\"average\",metric=\"TunnelIngressPacketDropTSMismatch\",resourceID=~\".*/$host\"}",
     "legendFormat": "Incoming"
    }
   ]
  }
 ]
}