{
 "title": "MongoDB RocksDB",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\", engine=\"rocksdb\"}, instance)"
   },
   {
    "name": "level",
    "label": "RocksDB Level",
    "query": "label_values(mongodb_mongod_rocksdb_files{cluster=~\"$cluster\",instance=\"$host\",level!=\"total\"}, level)"
   }
  ]
 },
 "panels": [
  {
   "title": "RocksDB Memtable Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_memtable_bytes{instance=\"$host\", type=\"total\"}/67108864"
    }
   ]
  },
  {
   "title": "RocksDB Block Cache Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_block_cache_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})) / node_memory_MemTotal{instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Document Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    }
   ]
  },
  {
   "title": "RocksDB Cache Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_memtable_bytes{instance=\"$host\"}",
     "legendFormat": "memtable_{{type}}"
    },
    {
     "expr": "mongodb_mongod_rocksdb_block_cache_bytes{instance=\"$host\"}",
     "legendFormat": "block_cache_total"
    }
   ]
  },
  {
   "title": "RocksDB Memtable Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_memtable_entries{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Block Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_block_cache_hits_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_rocksdb_block_cache_hits_total{instance=\"$host\"}[5m])/rate(mongodb_mongod_rocksdb_block_cache_misses_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_rocksdb_block_cache_misses_total{instance=\"$host\"}[5m])",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "RocksDB Write Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes / Sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_bytes_written_total{instance=\"$host\",type!=\"total\"}[$interval]) or irate(mongodb_mongod_rocksdb_bytes_written_total{instance=\"$host\",type!=\"total\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Read Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes / Sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_bytes_read_total{instance=\"$host\",type!=\"total\"}[$interval]) or irate(mongodb_mongod_rocksdb_bytes_read_total{instance=\"$host\",type!=\"total\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Level0 Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_read_latency_microseconds{instance=\"$host\",level=\"L0\",type=~\"(avg|min|max|P99)\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN Read Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_read_latency_microseconds{instance=\"$host\",level=~\"$level\",level!=\"L0\",type=\"avg\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN 99th Percentile Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_read_latency_microseconds{instance=\"$host\",level=~\"$level\",level!=\"L0\",type=\"P99\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB LevelN Maximum Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_read_latency_microseconds{instance=\"$host\",level=~\"$level\",level!=\"L0\",type=~\"(max)\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_compaction_seconds_total{instance=\"$host\", level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_seconds_total{instance=\"$host\", level=~\"$level\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Write Amplification",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_compaction_write_amplification{instance=\"$host\",level=~\"$level\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\", level=~\"$level\", type=~\"read.*\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\", level=~\"$level\", type=~\"read.*\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\", level=~\"$level\", type=~\"write.*\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\", level=~\"$level\", type=~\"write.*\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Key Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_compactions_total{instance=\"$host\", level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compactions_total{instance=\"$host\", level=~\"$level\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_compaction_file_threads{instance=\"$host\", level=~\"$level\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Level Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_files{instance=\"$host\", level=~\"$level\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "New row",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_size_bytes{instance=\"$host\", level=~\"$level\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "RocksDB Write Ahead Log Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_write_ahead_log_bytes_per_second{instance=\"$host\"}",
     "legendFormat": "Write Rate"
    }
   ]
  },
  {
   "title": "RocksDB Write Ahead Log Sync Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_write_ahead_log_writes_per_sync{instance=\"$host\"}",
     "legendFormat": "Writes per Sync"
    }
   ]
  },
  {
   "title": "RocksDB Flush Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\",level=~\"$level\"}[$interval]) or irate(mongodb_mongod_rocksdb_compaction_bytes_per_second{instance=\"$host\",level=~\"$level\"}[5m])",
     "legendFormat": "{{level}}_{{type}}"
    }
   ]
  },
  {
   "title": "RocksDB Pending Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_rocksdb_pending_compactions{instance=\"$host\"}",
     "legendFormat": "compactions"
    },
    {
     "expr": "mongodb_mongod_rocksdb_pending_memtable_flushes{instance=\"$host\"}",
     "legendFormat": "memtable_flushes"
    }
   ]
  },
  {
   "title": "RocksDB Stall Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_stalled_seconds_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_rocksdb_stalled_seconds_total{instance=\"$host\"}[5m])",
     "legendFormat": "Time Stalled"
    }
   ]
  },
  {
   "title": "RocksDB Stalls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_rocksdb_stalls_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_rocksdb_stalls_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Client Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{instance=\"$host\", type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_counters_total{instance=\"$host\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}