{
 "title": "Cross Server Graphs",
 "tags": [ "Insight" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values({__name__=~\"node_load1|mysql_up\", job!=\"prometheus\"}, group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "node_load1{group=~\"$group\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Combine CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "(1 - avg by(instance)(irate(node_cpu{instance=~\"$host\",mode='idle'}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "**Load Average**\n\nOn Linux, this is the number of processes which are in “running” state or in “uninterruptible sleep” state which typically corresponds to disk IO. You can also map LoadAvg to VMSTAT output – it is something like moving average of sum of “r” and “b” columns from VMSTAT.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "100 - 100 * (node_memory_MemAvailable{instance=~\"$host\"} or (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / (node_memory_MemTotal{instance=~\"$host\"} + 0.1)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) + rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval])) by (instance) or sum(irate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m]) + irate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) by (instance) or\nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval]) + max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) by (instance) or sum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]) + max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data Disc Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "1 - node_filesystem_free{instance=~\"$host\", mountpoint=\"/data\"}  / node_filesystem_size{instance=~\"$host\", mountpoint=\"/data\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "rate(node_disk_io_time_ms{device=\"sdb\", instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_io_time_ms{device=\"sdb\", instance=~\"$host\"}[5m])/1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "System Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host\"}",
     "legendFormat": "{{sysname}} | {{ release }} | {{domainname}}"
    }
   ]
  }
 ]
}