{
 "title": "Dell PowerEdge",
 "description": "Dell PowerEdge Overview",
 "tags": [ "Platform" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(dell_hw_chassis_current_reading, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(dell_hw_chassis_current_reading{customer=~\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(dell_hw_chassis_current_reading{customer=~\"$customer\",environment=~\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(dell_hw_chassis_current_reading{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\"},group)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(dell_hw_chassis_current_reading{customer=~\"$customer\",environment=~\"$environment\",project=~\"$project\",group=~\"$group\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Batteries\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Fans\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Intrusion\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Memory\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Power_Supplies\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Processors\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Temperatures\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_status{component=\"Voltages\",instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_storage_pdisk_status{instance=~\"$host\"})"
    },
    {
     "expr": "max by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_storage_vdisk_status{instance=~\"$host\"})"
    },
    {
     "expr": "avg by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_temps_reading{component=\"System_Board_Inlet_Temp\",instance=~\"$host\"})"
    },
    {
     "expr": "avg by(instance,ExpressServiceCode,ServiceTag,environment,project,group,customer,CabinetUnits)(dell_hw_chassis_temps_reading{component=\"System_Board_Exhaust_Temp\",instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "dell_hw_chassis_power_reading{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fan Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Revolutions per minute" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(dell_hw_chassis_fan_reading{instance=~\"$host\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}