{
 "title": "Kubernetes Cluster",
 "tags": [
  "Platform",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(machine_cpu_cores, customer)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(machine_cpu_cores{customer=\"$customer\"}, environment)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(machine_cpu_cores{customer=\"$customer\",environment=\"$environment\"}, project)"
   },
   {
    "name": "group",
    "label": "Cluster",
    "query": "label_values(machine_cpu_cores{project=\"$project\",environment=\"$environment\"},group)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(machine_cpu_cores{customer=\"$customer\",environment=\"$environment\",project=\"$project\",group=\"$group\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Total Cluster Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) / sum (machine_cpu_cores{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) / sum (machine_memory_bytes{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Filesystem Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/xvda.$\",id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/xvda.$\",id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/xvda.$\",id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/xvda.$\",id=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Network IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total Node Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(machine_cpu_cores{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\",nodeType=\"master\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(machine_cpu_cores{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\",nodeType=\"slave\"})"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace!~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace!~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace!~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{namespace!~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "System Services CPU and Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"kube-system|kubernetes-dashboard\",pod!=\"\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All Processes CPU and Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "All processes network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",group=\"$group\",environment=\"$environment\",customer=\"$customer\",project=\"$project\",kubernetes_io_hostname=~\"$node\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}