{
 "title": "VMware vSphere Overview",
 "tags": [ "Platform" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(vmware_host_boot_timestamp_seconds,environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hypervisors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_host_power_state{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usage{environment=\"$environment\"}) / sum(vmware_host_cpu_max{environment=\"$environment\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{environment=\"$environment\"}) / sum(vmware_host_memory_max{environment=\"$environment\"}) * 100"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "vmware_host_memory_max{environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(vmware_datastore_freespace_size{environment=\"$environment\",ds_name!~\"local-.*\"}) / sum(vmware_datastore_capacity_size {environment=\"$environment\",ds_name!~\"local-.*\"})) * 100"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (vmware_datastore_freespace_size{environment=\"$environment\",ds_name!~\"local-.*\"}) / (vmware_datastore_capacity_size{environment=\"$environment\",ds_name!~\"local-.*\"})) * 100"
    },
    {
     "expr": "vmware_datastore_capacity_size{environment=\"$environment\",ds_name!~\"local-.*\"}"
    },
    {
     "expr": " vmware_datastore_provisoned_size{environment=\"$environment\",ds_name!~\"local-.*\"} / vmware_datastore_capacity_size{environment=\"$environment\",ds_name!~\"local-.*\"}"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(vmware_host_power_state{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Max CPU availability in Mhz",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_max{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Total DataStorage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_datastore_capacity_size {environment=\"$environment\",ds_name!~\"local-.*\"})"
    }
   ]
  },
  {
   "title": "ESX Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{environment=\"$environment\"} / vmware_host_cpu_max{environment=\"$environment\"} * 100",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "ESX Host RAM Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_host_memory_usage{environment=\"$environment\"} / vmware_host_memory_max{environment=\"$environment\"} * 100",
     "legendFormat": "{{host_name}}"
    }
   ]
  }
 ]
}