{
 "title": "Azure Database for MySQL",
 "tags": [ "Databases" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_mysql, resourceID)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "azure_mysql{aggregation=\"average\",metric=\"cpu_percent\",resourceID=~\"/subscriptions/$subscription/.*\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "azure_mysql{aggregation=\"average\",metric=\"cpu_percent\",resourceID=~\"/subscriptions/$subscription/resource[gG]roups/$resourcegroup/providers/Microsoft.DB[fF]orMySQL/servers/.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"maximum\",metric=\"storage_limit\",resourceID=~\".*/$host\"}",
     "legendFormat": "Storage limit"
    },
    {
     "expr": "azure_mysql{aggregation=\"maximum\",metric=\"storage_used\",resourceID=~\".*/$host\"}",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "Serverlog Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"maximum\",metric=\"serverlog_storage_limit\",resourceID=~\".*/$host\"}",
     "legendFormat": "Storage limit"
    },
    {
     "expr": "azure_mysql{aggregation=\"maximum\",metric=\"serverlog_storage_usage\",resourceID=~\".*/$host\"}",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"active_connections\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "seconds",
   "valueName": "avg",
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"maximum\",metric=\"seconds_behind_master\",resourceID=~\".*/$host\"} or vector(0)"
    }
   ]
  },
  {
   "title": "CPU percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"cpu_percent\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"memory_percent\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Storage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"storage_percent\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Server Log storage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"serverlog_storage_percent\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "IO percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"average\",metric=\"io_consumption_percent\",resourceID=~\".*/$host\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "There are differences between API and portal.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_mysql{aggregation=\"total\",metric=\"network_bytes_ingress\",resourceID=~\".*/$host\"} or vector(0)",
     "legendFormat": "Network In"
    },
    {
     "expr": "azure_mysql{aggregation=\"total\",metric=\"network_bytes_egress\",resourceID=~\".*/$host\"} or vector(0)",
     "legendFormat": "Network Out"
    }
   ]
  }
 ]
}