{
 "title": "Azure SQL Elastic pool",
 "tags": [ "Databases" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(azure_sqlelasticpool, resourceID)"
   },
   {
    "name": "resourcegroup",
    "label": "ResourceGroup",
    "query": "azure_sqlelasticpool{aggregation=\"average\",metric=\"sessions_percent\",resourceID=~\"/subscriptions/$subscription/.*\"}"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "azure_sqlelasticpool{aggregation=\"average\",metric=\"sessions_percent\",resourceID=~\"/subscriptions/$subscription/resource[gG]roups/$resourcegroup/providers/Microsoft.Sql/servers/.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Operating load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"cpu_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"workers_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Workers"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"sessions_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "vCores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"cpu_limit\",resourceID=~\".*/$host.*\"}"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"storage_limit\",resourceID=~\".*/$host.*\"}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"storage_used\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"storage_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Tempdb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"tempdb_data_size\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"tempdb_log_size\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Log"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"tempdb_log_used_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"physical_data_read_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"log_write_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": "Log"
    }
   ]
  },
  {
   "title": "In-Memory OLTP storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_sqlelasticpool{aggregation=\"average\",metric=\"xtp_storage_percent\",resourceID=~\".*/$host.*\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}