{
 "title": "MongoDB WiredTiger",
 "tags": [ "Databases" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(mongodb_up, group)"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{group=\"$group\", engine=\"wiredTiger\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_byte{instance=\"$host\"} or (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers_bytes{instance=\"$host\"} + node_memory_Cached_bytes{instance=\"$host\"})) / node_memory_MemTotal_bytes{instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"read\"}[5m])",
     "legendFormat": "Read into"
    },
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$host\", type=\"written\"}[5m])",
     "legendFormat": "Written from"
    }
   ]
  },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{instance=\"$host\"}",
     "legendFormat": "Cursors"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_sessions_total{instance=\"$host\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{instance=\"$host\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{instance=\"$host\"}[5m])",
     "legendFormat": "current"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=\"$host\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$host\", type=\"total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{instance=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=\"$host\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}