{
 "title": "MySQL Table Statistics",
 "tags": [ "Databases" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   { "name": "group", "label": "Group", "query": "label_values(mysql_up, group)" },
   {
    "name": "host",
    "label": "Host",
    "query": "mysql_up{group=\"$group\"}"
   }
  ]
 },
 "panels": [
  { "title": "Largest Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Largest Tables by Row Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_rows{instance=\"$host\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Largest Tables by Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_size{instance=\"$host\", component!=\"data_free\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_info_schema_table_size{instance=\"$host\", component!=\"data_free\"})",
     "legendFormat": "Data + Index Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_info_schema_table_size{instance=\"$host\", component=\"data_free\"})",
     "legendFormat": "Freeable Size"
    }
   ]
  },
  {
   "title": "Most Fragmented Tables by Freeable Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, sum(mysql_info_schema_table_size{instance=\"$host\", component=\"data_free\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Table Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "The next two graphs are available only for [Percona Server](https://www.percona.com/doc/percona-server/5.6/diagnostics/user_stats.html) and [MariaDB](https://mariadb.com/kb/en/mariadb/user-statistics/) and require `userstat` variable turned on."
  },
  { "title": "Rows read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Top Tables by Rows Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_info_schema_table_statistics_rows_read_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_info_schema_table_statistics_rows_read_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Rows Changed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Top Tables by Rows Changed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_info_schema_table_statistics_rows_changed_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_info_schema_table_statistics_rows_changed_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  { "title": "Auto Increment Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Tables by Auto Increment Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, mysql_info_schema_auto_increment_column{instance=\"$host\"} / mysql_info_schema_auto_increment_column_max{instance=\"$host\"})",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  }
 ]
}