{
 "title": "MySQL Performance Schema Wait Event Analyses",
 "tags": [ "Databases" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,1m,5m,1h,6h,1d" },
   { "name": "group", "label": "Group", "query": "label_values(mysql_up, group)" },
   {
    "name": "host",
    "label": "Host",
    "query": "mysql_global_variables_performance_schema{group=\"$group\"}"
   },
   {
    "name": "event",
    "label": "Event",
    "query": "label_values(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\"}, event_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Count - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Load - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  },
  {
   "title": "Avg Wait Time - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",event_name=~\"$event\"}[$interval])/rate(mysql_perf_schema_events_waits_total{instance=\"$host\",event_name=~\"$event\"}[$interval]) or irate(mysql_perf_schema_events_waits_seconds_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])/irate(mysql_perf_schema_events_waits_total{instance=\"$host\",instance=\"$host\",event_name=~\"$event\"}[5m])",
     "legendFormat": "{{event_name}} "
    }
   ]
  }
 ]
}